# Generated by Django 4.1.13 on 2024-04-13 09:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attribute",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Атрибут",
                "verbose_name_plural": "Атрибуты",
            },
        ),
        migrations.CreateModel(
            name="Catalog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "3. Каталог",
                "verbose_name_plural": "3. Каталоги",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "1. Категория",
                "verbose_name_plural": "1. Категории",
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("price", models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ("count", models.PositiveIntegerField()),
                ("upc", models.CharField(blank=True, max_length=64, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "catalog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="items", to="products.catalog"
                    ),
                ),
            ],
            options={
                "verbose_name": "4. Товар",
                "verbose_name_plural": "4. Товары",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="products", to="products.category"
                    ),
                ),
            ],
            options={
                "verbose_name": "2. Продукт",
                "verbose_name_plural": "2. Продукты",
            },
        ),
        migrations.CreateModel(
            name="ItemAttribute",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value", models.CharField(max_length=100)),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itemattributes",
                        to="products.attribute",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="itemattributes", to="products.item"
                    ),
                ),
            ],
            options={
                "verbose_name": "Конкретный параметр",
                "verbose_name_plural": "Конкретные параметры",
            },
        ),
        migrations.AddField(
            model_name="catalog",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="catalogs", to="products.product"
            ),
        ),
        migrations.AddField(
            model_name="attribute",
            name="catalog",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="attributes", to="products.catalog"
            ),
        ),
    ]
