# Generated by Django 4.1.13 on 2024-04-15 03:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="item",
            constraint=models.UniqueConstraint(fields=("catalog", "upc"), name="unique_item_name_per_upc"),
        ),
    ]
