# Generated by Django 4.1.13 on 2024-04-15 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("holder", "0001_initial"),
        ("products", "0002_item_unique_item_name_per_upc"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="poster",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="holder.imageholder",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="video",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="holder.videoholder",
            ),
        ),
    ]
