# Generated by Django 4.1.13 on 2024-04-15 06:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_item_poster_item_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
