# Generated by Django 4.1.13 on 2024-04-16 05:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0005_item_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="favourites",
            field=models.ManyToManyField(blank=True, related_name="favourites", to=settings.AUTH_USER_MODEL),
        ),
    ]
