# Generated by Django 4.1.13 on 2024-04-22 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_alter_order_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0007_review"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cheque",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("pdf", models.FileField(max_length=500, upload_to="files/certificates/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="cheques", to="orders.order"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="cheques", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
