# Generated by Django 4.1.13 on 2024-04-22 05:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("новый", "Status New"),
                    ("в доставке", "Status Delivery"),
                    ("завершен", "Status Finished"),
                    ("отменен", "Status Canceled"),
                    ("оплачен", "Status Completed"),
                ],
                default="новый",
                max_length=30,
            ),
        ),
    ]
