GET http://localhost:8000/api/v1/items/
# Authorization: Bearer {{token}}

###

GET http://localhost:8000/api/v1/items/?exclude[]=count&include[]=catalog.product.*
# Authorization: Bearer {{token}}

###
