version: "3.3"

volumes:
  pg_data:

services:
  db:
    image: postgres:alpine
    restart: always
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  rabbit:
    image: rabbitmq:3-management-alpine
    ports:
      - "5677:5672"
      - "15677:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: pass
