# Generated by Django 4.1.13 on 2024-04-15 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0004_item_description"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Basket",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ],
            options={
                "verbose_name": "Корзина товаров",
                "verbose_name_plural": "Корзина товаров",
            },
        ),
        migrations.CreateModel(
            name="BasketRow",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("qty", models.PositiveIntegerField(default=1)),
                (
                    "basket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="basket_rows", to="baskets.basket"
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="basket_rows", to="products.item"
                    ),
                ),
            ],
            options={
                "verbose_name": "заказ в корзине",
                "verbose_name_plural": "заказы в корзине",
            },
        ),
        migrations.AddField(
            model_name="basket",
            name="items",
            field=models.ManyToManyField(
                blank=True, related_name="baskets", through="baskets.BasketRow", to="products.item"
            ),
        ),
        migrations.AddField(
            model_name="basket",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="baskets", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
