version: "3.3"

services:

  nginx:
    image: caddy:2.7-alpine
    restart: always
    network_mode: "host"
    cap_add:
      - NET_ADMIN
    volumes:
      - ./data:/data
      - ./config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
