# Generated by Django 4.1.13 on 2024-04-15 05:00

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ImageHolder",
            fields=[
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("file", models.ImageField(max_length=500, upload_to="files/images/")),
            ],
            options={
                "verbose_name": "изображение",
                "verbose_name_plural": "изображения",
            },
        ),
        migrations.CreateModel(
            name="VideoHolder",
            fields=[
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("file", models.FileField(max_length=500, upload_to="files/videos/")),
            ],
            options={
                "verbose_name": "видео-файл",
                "verbose_name_plural": "видео-файлы",
            },
        ),
    ]
