# Generated by Django 4.1.13 on 2024-04-25 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TgUser",
            fields=[
                ("id", models.CharField(max_length=100, primary_key=True, serialize=False)),
                ("username", models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="tg_user", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
