name: ci-cd

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

env:
  USERNAME: antuanuran
  IMAGE_NAME: petshop

jobs:
  tests:
    runs-on: ubuntu-latest
#    services:
#      postgres:
#        image: postgres:alpine
#        env:
#          POSTGRES_USER: pytest
#          POSTGRES_PASSWORD: pytest
#        options: >-
#          --health-cmd pg_isready
#          --health-interval 10s
#          --health-timeout 5s
#          --health-retries 5
#        ports:
#          - 5432:5432
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Check black .
        run: black --check .

      - name: Check isort .
        run: isort -c .

      - name: Check flake8 .
        run: flake8 .

#      - name: Test with pytest
#        run: pytest
#        env:
#          POSTGRES_USER: pytest
#          POSTGRES_PASSWORD: pytest
#
  build:
    if: github.event_name == 'push'
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.USERNAME }}
          password: ${{ secrets.PASSWORD_HUB }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ env.USERNAME }}/${{ env.IMAGE_NAME }}:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Connect
        uses: appleboy/ssh-action@master
        with:
          host: 79.174.92.212
          username: root
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /srv/deploy/petshop/server_project
            docker pull ${{ env.USERNAME }}/${{ env.IMAGE_NAME }}:latest
            docker-compose down && docker-compose up -d && docker ps
